### ISSUE TITLE
Vim flickering due to redraws in echo area

### ISSUE THREAD

**Issue by alexanderjeurissen** [ido-nvim/core#19] opened 2021-02-23 21:08 UTC
### Context

Seems that there is way more flickering in the redrawing that occurs due to ido.nvim renders.

See attached screen recording

https://user-images.githubusercontent.com/1220084/108908469-a0e18800-7623-11eb-8738-9bb57ce99682.mov

**Comment by shoumodip** [comment] 2021-02-24 11:15
That's strange, considering ido never calls `redraw`. I need a little bit more information to even *begin* to diagnose.
- Number of items you are filtering
- Your terminal emulator
- Multiplexer you are using (if any)
- Your neovim version

Another thing I have noticed is that in this screencast the real terminal cursor is not hidden. It is visible in the bottom right corner. That is *not* supposed to happen. I am using the `blend` property of the highlighting in Neovim 0.5+ to hide the real cursor. Maybe that and the flickering have a common cause. Are you using `tmux`, because that is known to cause severe slowdowns and key input latency sometimes.

**Comment by alexanderjeurissen** [comment] 2021-02-24 13:29
> That's strange, considering ido never calls `redraw`. I need a little bit more information to even _begin_ to diagnose.
> 
> * Number of items you are filtering
Filtering the output of `rg --files --ignore --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore` in my home directory which comes down to 399,985 items.

> * Shell
fish, version 3.1.2

> * Your terminal emulator
alacritty 0.5.0

> * Multiplexer you are using (if any)
tmux next-3.3

> * Your neovim version

```
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210131-4645-rsraua/build/config -I/tmp/neovim-20210131-4645-rsraua/src -I/usr/local/include -I/tmp/neovim-20210131-4645-rsraua/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210131-4645-rsraua/build/src/nvim/auto -I/tmp/neovim-20210131-4645-rsraua/build/include
Compiled by alexanderjeurissenlocal@Alexanders-MacBook-Pro-16-inch-2019

Features: +acl +iconv +tui
See ":help feature-compile"
```
> 
> Another thing I have noticed is that in this screencast the real terminal cursor is not hidden. It is visible in the bottom right corner. That is _not_ supposed to happen. I am using the `blend` property of the highlighting in Neovim 0.5+ to hide the real cursor. Maybe that and the flickering have a common cause. Are you using `tmux`, because that is known to cause severe slowdowns and key input latency sometimes.

It seems this is only the case when `termguicolors` is off, when I enable `termguicolors` the blending works properly, however I still have the same flickering behavior.

**Comment by alexanderjeurissen** [comment] 2021-02-24 13:30
It might be an issue with the emulator, when trying tmux with plain old `terminal.app` I see less redraw quirks. Interesting as `Alacritty` is GPU powered and praises itself for very fast redraws.

**Comment by shoumodip** [comment] 2021-02-25 06:06
Yeah it's an Alacritty problem. I installed `alacritty` and it was flickering like Hades even without tmux, whereas suckless `st` had no such problem. Looks like less is more after all!

Closing this, since this seems to be a terminal problem, not an Ido problem.

**Comment by alexanderjeurissen** [comment] 2021-02-28 23:49
Re-opening this given that the issue is still present in varying terminal emulators.

Some of the ones I've tried:

- Kitty
- Alacritty
- Terminal.app
- Iterm

The issue is most visible in `Alacritty` as it has a very low redraw / refresh rate. 
When looking at the `ui` code it seems that the cause is excessive redraws in the `ui.clear` method that invokes `mode`

```vim
							*:mod* *:mode*
:mod[e]			Clears and redraws the screen.
```

The key problem here is:
> **Clears** and redraws the screen

Meaning we clear the screen completely then redraw it, which results in the perceived flickering.

When replacing `mode` with `redraw!` the flickering in "minimal" mode is completely gone, irrespective of what terminal emulator or multiplexer is used:

```vim
							*:redr* *:redraw*
:redr[aw][!]		Redraws pending screen updates now, or the entire
			screen if "!" is included.  To CLEAR the screen use
			|:mode| or |CTRL-L|.
			Useful to update the screen during a script or
			function (or a mapping if 'lazyredraw' set).
```

I attached a before / after screen recordings showing the gigantic leap in rendering performance when using redraw instead of mode:

**Before (using mode, current behavior):**
https://user-images.githubusercontent.com/1220084/109437861-965e2e80-7a27-11eb-9bab-ebd398f49bc2.mov

**After (using redraw!):**

https://user-images.githubusercontent.com/1220084/109437942-e50bc880-7a27-11eb-81bc-128494b6885b.mov


---


Only caveat is that in my testing vertical mode behaves odd and draws twice before redrawing. With your help I'm sure we can fix that and improve rendering performance for all as Tmux users out there.

**Comment by shoumodip** [comment] 2021-03-01 11:36
Huh, looks like `redraw` was better all along. I used `redraw` earlier in Ido, but got paranoid it was slowing it down, so I replaced it with `mode`. And now I find out it was as stupid as replacing C with python to gain speed lol.

Huge kudos to you for spotting that. BTW sorry for not checking up on whether you are a collaborator sooner. I kinda assumed github would do that automatically do that once you were a member of `ido-nvim`.

**Comment by shoumodip** [comment] 2021-03-01 11:54
Speaking of rendering, this is what I am currently implementing.
```lua
render_sequence = {
   "prompt",
   "query",
   "results",
}
```

For example
```
layout.new{
   name = "reverse",

   results_start = "    ",
   results_selected = "\n -> ",
   results_separator = "\n    ",
   results_end = "\n",

   maximum_height = 10,
   dynamic_resize = true,

   render_sequence = {
      {"results", reverse = true, lines_limit = 9},
      "prompt",
      "query",
   }
}
```

creates a layout which looks like

![pic-full-210301-1713-22](https://user-images.githubusercontent.com/70207920/109493606-c6064880-7ab2-11eb-8cd7-0ac0b18ec4a6.png)

WDYT?

**Comment by alexanderjeurissen** [comment] 2021-03-01 20:24
> Speaking of rendering, this is what I am currently implementing.
> 
> ```lua
> render_sequence = {
>    "prompt",
>    "query",
>    "results",
> }
> ```
> 
> For example
> 
> ```
> layout.new{
>    name = "reverse",
> 
>    results_start = "    ",
>    results_selected = "\n -> ",
>    results_separator = "\n    ",
>    results_end = "\n",
> 
>    maximum_height = 10,
>    dynamic_resize = true,
> 
>    render_sequence = {
>       {"results", reverse = true, lines_limit = 9},
>       "prompt",
>       "query",
>    }
> }
> ```
> 
> creates a layout which looks like
> 
> ![pic-full-210301-1713-22](https://user-images.githubusercontent.com/70207920/109493606-c6064880-7ab2-11eb-8cd7-0ac0b18ec4a6.png)
> 
> WDYT?


Personally  I'm not sure if we need to expand the layout API at this point, personally I think sticking with the advices we have now maybe with a couple of additional advices should suffice. 

I think we have a lot of flexibility with the advices, and I think writing a more structured API around it diminishes this aspect of IDO.

If you have the chance, can you take a look at the open PR ? #21 should be a quick review and would really open up flexibility for package authors.

**Comment by shoumodip** [comment] 2021-03-02 04:41
Unfortunately the rendering system is not compatible with advices. Let me elaborate a bit. When rendering, the function needs to return exactly when it can render no more, otherwise it shall calculate the rendering for tokens it need not render, and let me tell you, that is REALLY memory and time intensive. Ido already slows down when working with large lists, introducing advices in the renderer will make it unusable with huge lists.

Therefore I feel that we need to have the rendering system's api separate from the rest. Advices are a no-no there. ATM this is the only solution I feel which will make the renderer at least partially extensible.

BTW I merged in the PR, just so you know. Cheers :)

**Comment by shoumodip** [comment] 2021-03-02 05:30
I could find no way to make this work with no flickering in alacritty. Believe me, I installed *every* single terminal emulator in existence and tried this out, and they all worked without flickering, save alacritty. Kitty, urxvt, xterm, konsole, gnome-terminal, xfce4-terminal, you name it. Unfortunately this seems to be a problem noticed before in alacritty. See [#3859](https://github.com/alacritty/alacritty/issues/3859)

The only good news is that the "horizontal mode" with height of 1 manages to not flicker in alacritty. So if you are content with that, no problem then. Otherwise I really don't know what to do. I have tried every single way of fixing it but to no avail.

**Comment by alexanderjeurissen** [comment] 2021-03-04 11:25
> Unfortunately the rendering system is not compatible with advices. Let me elaborate a bit. When rendering, the function needs to return exactly when it can render no more, otherwise it shall calculate the rendering for tokens it need not render, and let me tell you, that is REALLY memory and time intensive. Ido already slows down when working with large lists, introducing advices in the renderer will make it unusable with huge lists.
> 
> Therefore I feel that we need to have the rendering system's api separate from the rest. Advices are a no-no there. ATM this is the only solution I feel which will make the renderer at least partially extensible.
> 
> BTW I merged in the PR, just so you know. Cheers :)

Makes sense, thanks for elaborating.

Let's open a separate issue for the extensible layouts, I think this issue is getting a bit messy at this point. There is definitely some things to discuss here. 

Another idea, maybe let's add `discussions` to the repo ? that makes it easier to do quick back and forth communication.
https://docs.github.com/en/discussions

**Comment by alexanderjeurissen** [comment] 2021-03-04 11:32
> I could find no way to make this work with no flickering in alacritty. Believe me, I installed _every_ single terminal emulator in existence and tried this out, and they all worked without flickering, save alacritty. Kitty, urxvt, xterm, konsole, gnome-terminal, xfce4-terminal, you name it. Unfortunately this seems to be a problem noticed before in alacritty. See [#3859](https://github.com/alacritty/alacritty/issues/3859)
> 
> The only good news is that the "horizontal mode" with height of 1 manages to not flicker in alacritty. So if you are content with that, no problem then. Otherwise I really don't know what to do. I have tried every single way of fixing it but to no avail.

@shoumodip I'm able to reproduce the issue in all of the emulators you mentioned when run inside of `Tmux` or `screen`.
This also applies to `horizontal` mode which with the `:mode` implementation flickers as well.

Given that we got the flickering solved in horizontal mode when using `redraw!` I think that something with our current rendering system is buggy and if we solve it we'll have lag free rendering.

My current take is that our `ui` module is too complex as it serves too many use-cases.
Current implementation supports both horizontal and vertical modes, and the only way this works is by calculating the total characters (instead of lines) and multiply them by the `max_lines` option. 

We could drastically simplify the rendering logic if we separate these two use-cases, one renderer for horizontal mode and one for vertical, that way we can also address each in isolation. It also addresses your custom layout idea.

Furthermore I think there will be community created layouts / renderers in the future as well. For instance maybe one that renders in a floating window, or one that renders in a Tmux split, one that renders inside the current active window, etc.

What timezone are you in ? maybe we can jump in a call over the weekends and see if we can pair program / brainstorm on solutions.

**Comment by shoumodip** [comment] 2021-03-05 10:00
Could we make Ido sort of like Helm, you know. Like the items would be rendered in a separate window, and the prompt in the echo area? That way, we could also allow for matched characters highlighting. It would also drastically improve the rendering performance. I tried out a naive rendering implementation that way, and it didn't flicker even once in Neovim in tmux in alacritty.

**Comment by alexanderjeurissen** [comment] 2021-03-05 11:21
> Could we make Ido sort of like Helm, you know. Like the items would be rendered in a separate window, and the prompt in the echo area? That way, we could also allow for matched characters highlighting. It would also drastically improve the rendering performance. I tried out a naive rendering implementation that way, and it didn't flicker even once in Neovim in tmux in alacritty.

I think one of the things I like about Ido is that the layout is very similar to IDO in emacs land, meaning the reverse layout in vertical mode and the one line horizontal mode.

echo area prompt + window will likely result in the prompt being at the bottom at which point I feel we lose the differentiation of ido compared to other fuzzy searchers.

I do agree however that rendering performance is easier If the items are listed in an actual buffer instead of the echo area (which needs to be redrawn in full). 

**What I'm proposing is this:**

1. Fix the horizontal mode with the `redraw!` change I suggested.
2. Remove built-in support for the vertical mode 
3. Create a separate packages for different layouts (such as the one you suggested).

I think this is in line with how IDO works in emacs as well, vertical mode is a separate extension in emacs and I think that makes sense as it keeps the `core` very small.

**Comment by shoumodip** [comment] 2021-03-05 11:45
I think I already changed `mode` to `redraw` in the core.

Also vertical mode is not a package which implements Ido in itself. It is merely a
```emacs-lisp
(setq
 ido-max-window-height 10
 ido-decorations
      '("\n -> "
        ""
        "\n    "
        ""
        "["
        "]"
        " [No match]"
        " [Matched]"
        " [Not readable]"
        " [Too big]"
        " [Confirm]"))
```

**Comment by alexanderjeurissen** [comment] 2021-03-05 12:10
> I think I already changed `mode` to `redraw` in the core.
> 

Awesome I'll check that out. 

> 
> 
> Also vertical mode is not a package which implements Ido in itself. It is merely a
> 
> ```emacs-lisp
> 
> (setq
> 
>  ido-max-window-height 10
> 
>  ido-decorations
> 
>       '("\n -> "
> 
>         ""
> 
>         "\n    "
> 
>         ""
> 
>         "["
> 
>         "]"
> 
>         " [No match]"
> 
>         " [Matched]"
> 
>         " [Not readable]"
> 
>         " [Too big]"
> 
>         " [Confirm]"))
> 
> ```

Are you sure ? 

https://github.com/creichert/ido-vertical-mode.el

Regardless I think there is something to be said for making Ido/core only ship with horizontal mode. It keeps the core nice and tidy whilst still allowing the community to build custom layouts and renderers.

**Comment by shoumodip** [comment] 2021-03-05 13:57
Do you think we should combine layouts and renderers? Like the default layout of Ido *is* the default layout. So instead of `ido.layout.results_start` or whatever, we do `ido.render.decorations.results_start`, where `ido.render` is the renderer which ships with Ido by default.

I am saying this because custom renderers might render in a completely different way to the "traditional" Ido layout, so I think it would be prudent to allow for custom layout options per renderer.

WDYT?

**Comment by shoumodip** [comment] 2021-03-06 05:54
I made vertical mode the only mode. Also now you should be able to create custom renderers. See the documentation [here](https://github.com/ido-nvim/docs/blob/main/markdown/render.md).

**Comment by shoumodip** [comment] 2021-03-22 16:18
Closing this, considering the problem is solved.

**Closed by shoumodip** 2021-03-22 16:18 UTC
Labels: question
